### ISSUE TITLE
Missing relationship data causes parent data to not be returned

### ISSUE THREAD

**Issue by molexx** [introproventures/graphql-jpa-query#101]
If a query nests to a relationship and there are no rows for that relationship then the parent's data is not returned.

e.g.:
```
query {
    Humans {
        select {
            id
            name
            homePlanet
        }
    }
}
```
returns 5 humans. Some have a homePlanet of null and that's fine.

But if you also want to see those humans' favoriteDroid:
```
query {
    Humans {
        select {
            id
            name
            homePlanet
            favoriteDroid {
              name
            }
        }
    }
}
```
it only returns 2 humans. Those who don't have a favoriteDroid aren't listed. I think they should be listed and just have a favouriteDroid of null?

**Comment by igdianov** [comment]
@molexx Good catch! I have created the PR to fix this. Do you think it will make sense to apply JPA schema semantics in order to build queries based on `optional` attribute specified using JPA's  association annotations:

```
    /** 
     * (Optional) Whether the association is optional. If set 
     * to false then a non-null relationship must always exist.
     */
    boolean optional() default true;
```

**Comment by molexx** [comment]
Thanks!

That makes sense... But does JPA enforce that anyway when it runs the query and tries to build its object graph?

**Comment by igdianov** [comment]
I think Hibernate persistence provider does use `optional` parameter on association annotations as a hint to create query for fetch graph at runtime when loading the entities. For example, relations of the actual entity specified with optional=false result in an INNER JOIN to their respective relation when loaded, whereas relations specified with optional=true result in LEFT JOINs. 

I had struggled with this when building HSQL query criteria for `@ManyToMany` association attributes using `INNER JOIN`, because Hibernate would add another `LEFT OUTER JOIN` to the query automatically and I could not understand why until now. Apparently, `@ManyToMany` is always optional, so Hibernate always uses left outer join to fetch data.

It would make sense to mimic default Hibernate behavior and derive default join type from `optional` attribute on the provided associations to build the query. At the same time, I think it is best not to be very opinionated about it and allow to override the the association join type in the actual query, i.e.

```
    Humans {
        select {
            id
            name
            homePlanet
            favoriteDroid(optional: true) {
              name
            }
        }
    }
```
The default value of the optional argument in GraphQL schema will be derived from JPA annotation where allowed, 

```
    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumn(name = "favorite_droid_id")
    Droid favoriteDroid;
```

What do you think?

**Comment by molexx** [comment]
Yes that sounds neat and flexible. Thanks!
