### ISSUE TITLE
Pagination not return correct number of records

### ISSUE THREAD

**Issue by MurrayFurtado** [introproventures/graphql-jpa-query#146]
I am using v0.3.25 running against Oracle, and I execute the following query:

`      query { 
        PositionCurrents (page: {start:1, limit: 100}, where : {
                portfolio: { id : { EQ : 1110 }, currentFlag : { EQ : "y"} },
                businessDate: { EQ : "2019-05-30T00:00:00.000Z" }
      }) {
        pages
        total
        select {
          	id,... etc
} 
}
`

The pages and total returned contain in the results contain the right numbers - eg pages: 4, total: 375
BUT the 'select' payload only contains 50 results. Is this a bug or am I doing something wrong? 

Also +1 for an offset/limit based paging solution.

Thanks

**Comment by MurrayFurtado** [comment]
After digging in the source code, the problem seems to be that in GraphQLJpaQueryDataFetcher only distinct records are being returned because of the line - 

 Collection<?> resultList = isDistinct ? new LinkedHashSet(query.getResultList()) : query.getResultList();

I think if the resultList size doesn't equal the pageSize an exception should be returned.  Also how does one set the isDistinct flag?

**Comment by Crashou59** [comment]
U can set isDistinct flag on ur shema builder, ex on ur configuration class : 
`@Bean
@ConditionalOnMissingBean(GraphQLSchemaBuilder.class)
public GraphQLSchemaBuilder graphQLSchemaBuilder(final EntityManager entityManager) {
			return new GraphQLJpaSchemaBuilder(entityManager).setDefaultDistinct(false);
}`

**Comment by igdianov** [comment]
@MurrayFurtado Can you extract your use case and post an example that reproduces the problem?

Do your entities implement equals and hashCode correctly?

**Comment by MurrayFurtado** [comment]
I believe this was due to an error on my part. I am closing this issue. Thanks.

**Comment by igdianov** [comment]
FYI. The list of entities returned by the getResultList method may contain duplicates if the SQL query joins the associated database records, and the result set consists of combinations of a parent record with each child record. Unfortunately, Hibernate doesn’t resolve these duplicates by default, so the data fetcher need to deal with this by applying distinct to root entities of the fetch result. 

In order to apply distinct correctly, the entities must implement equals and hashCode. This is also important for JPA persistence provider, i.e. http://www.laliluna.de/jpa-hibernate-guide/ch06s06.html
